apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: core-deployment 
spec: 
  selector: 
    matchLabels: 
      app: core 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: core 
    spec: 
      containers: 
      - name: core 
        image: demoacrcoream.azurecr.io/dotnetcore:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: core-service 
spec: 
  selector: 
    app: core 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer
